### ISSUE TITLE
[QUESTION] Modularity

### ISSUE THREAD

**Issue by Asfolny** [vr0n/talist#2]
Currently the src nim file is just one large file, many things could be split off.
Really this is personal preference, but I do believe the only real thing the talist.nim file should do, is import all the needed files, and then initialization.

Checking the db you could place inside a database.nim file for example, along with all the other things, on import it could then check, and expose a few functions (like getLists).

So the question is, will this be done?

**Comment by Asfolny** [comment]
Adding onto this, a config could be imported too, with the home consts, the db placement consts, etc.
I tried moving the db during my tests (because .config/talist/src is strange when everything else just sits in a bare .config/<app>/), and the database name came up multiple times instead of also just being a const

On that note, but this might be a separate issue, the database check opens the db, creates the tables, then closes it, only for you to immediately again open it below the check... why?

A third worthy note, the db is in a let, but the database connection itself is never mutated (or at least it definitely shouldn't be), const would be worth a try

**Comment by vr0n** [comment]
I would like to do this. When I started writing talist, it was clear that the basic functionality could be done in fewer than 100 lines of code, which I thought was small enough to keep in one file. However, after adding some formatting, the help menu, extra features, and a few other things the code ballooned into something much bigger. 

I don't do a lot of programming, so I'm learning the "best practices" as I go. I tried making things modular, but I hit a few errors with dependencies and variable declaration, so I won't be adding this until I get more familiar with nimlang. 

Thank you for the suggestions, though! I will make these updates soon!

**Comment by Asfolny** [comment]
No problem at all, I'll try taking a stab at this sometime tomorrow, can put that inside a draft pr, along other general improvements

After that I can try for the time tracking, that was also me btw
Adding more, before you refactor the whole thing would make the refactoring more work

As a last note, what exactly do you mean "over the network"?

As a general sync with some remote server, where your local things can be different, specifically you could have more locally than on your remote, but for the things you both have, remote (like due_date) takes priority, with a command to compare, for say a warning that you have more than the remote?

Or something else?
