### ISSUE TITLE
[Proposal] Adding a license

### ISSUE THREAD

**Issue by Asfolny** [vr0n/talist#6]
GitHub defaults a project without license something they specify [here](https://choosealicense.com/no-permission/), but it entails that nobody except the original copy right holder (project owner) can copy, distribute or modify, the keys here being modify and distribute (in my opnion)

Now, that only becomes a problem if I get accused or asked to take my stuff down, which I kinda doubt will happen, I'm more proposing to add a license to indicate what type of project this is, I think GPL would be the most fitting, because it says "this is free software, and anyone who uses this, makes a derivative work needs to opensource their stuff too".
Disclaimer: I'm not a laywer, that's just what it boils down to in my interpretation.

**Comment by vr0n** [comment]
I had specified the license in the talist.bimble file (as `license = GPL v2`), but the license itself is now included. 

Thank you for catching that!
